on:
  push:
    branches:
      - main # default branch

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      # - run: sed -i -e 's/"dependencies"/"peerDependencies"/1' package.json
      - run: npm install
      # - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
